#!/bin/sh
stty -F /dev/ttyUSB0 cs8 9600 ignbrk -brkint -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
socat tcp-listen:7778,fork /dev/ttyUSB0 &
./flip | socat stdin tcp-connect:localhost:7778
